### ISSUE TITLE
BIP buffer ?

### ISSUE THREAD

**Issue by kaidokert** [foonathan/array#4]
Just an idea, but it kind of looks like Bip buffer implementation would fit on top of block storage concept here quite well. 
Key word being 'contiguous memory container'. ( https://github.com/willemt/bipbuffer , https://www.codeproject.com/Articles/3479/The-Bip-Buffer-The-Circular-Buffer-with-a-Twist ) 

I'll try take a stab at getting something working, any pointers for the interface design ?

**Comment by foonathan** [comment]
It doesn't work with the requirements right now, as the elements are not all stored contiguously in memory behind each other, but in two different regions if the buffer has just overflowed (there are elements at the front, then empty space, then at the back). I need to figure out how to do that properly before implementing it.
