### ISSUE TITLE
Noob friendly decision tree

### ISSUE THREAD

**Issue by Manu343726** [foonathan/array#5]
Something like https://ned14.github.io/outcome/use-matrix/, for fools like me who feel overwhelmed by the feature list.

**Comment by foonathan** [comment]
Something like this?

In case you don't know what to use.
The container decision tree helps you pick a container,
the block storage decision tree helps you pick a block storage.

## Container Decision Tree

> When in doubt, use `std::vector`.

The problem with that approach:
In this library, *all* containers are `std::vector`!

You want to store:

* … just some objects of type `T`.
  Do you want often need to check whether `T` is already present or look it up based on a member?
    * Yes. Do you have a hash function for `T`?
        * Yes: Use some hash set from another library (but not `std::unordered_(multi)set`).
        * No:
            * Duplicates are not allowed: `array::flat_set<T>`
            * Duplicates are allowed: `array::flat_multiset<T>`
    * No. Do you want to access elements by index and/or the order is important?
        * Yes: `array::array<T>`
        * No: `array::bag<T>`

* … a mapping of `Key` to `Value`.
 Do you have a hash function for `Key`?
    * Yes: Use some hash map from another library (but not `std::unordered_(multi)map`).
    * No:
        * Duplicates are not allowed: `array::flat_map<Key, Value>`
        * Duplicates are allowed: `array::flat_multimap<Key, Value>`

* … a variant of `T1`, `T2`, …, `Tn`.
  Do you want to access elements by index and/or the order is important?
    * Yes: Repeat with `T = std::variant<T1, T2, …, Tn>`.
    * No: `array::variant_bag<BlockStorage, T1, T2, …, Tn>`.

## Block Storage Decision Tree

What do you know about the number of objects in the container?

* It is at most `N` where `N` is small enough that I can waste unused space: `array::block_storage_embedded<N * sizeof(T)>`.
* It is often `N` where `N` is small (single digit) but sometimes larger.
  Do you have a custom allocator?
    * Yes: `array::block_storage_heap_sbo<N * sizeof(T), MyCustomAllocator>`
    * No: `array::block_storage_heap_sbo<N * sizeof(T), array::new_heap>`.
  You can also use the `array::small_XXX` convenience aliases.
* I don't know anything.
  Do you have a custom allocator?
    * Yes: `array::block_storage_heap<MyCustomAllocator>`.
    * No: `array::block_storage_default` or just ignore the template parameter all together.

If you care about growth factors:
Look at the defaulted template parameters in the block storage.

If you have a fancy allocator that can decide the growth factors by itself:
Implement your own `BlockStorage`.

**Comment by Manu343726** [comment]
That looks great. I would also mention views, or at least directly reference what views you take from each container
