### ISSUE TITLE
Conversion from array views to char**

### ISSUE THREAD

**Issue by Manu343726** [foonathan/array#7]
Hi,

I'm trying to invoke LLVM's argument parser programaticaly (i.e. not from main with main args) and I was wondering if the array library could help me there. The issue is that [`llvm::ParseCommandLineOptions`](https://llvm.org/docs/CommandLine.html#the-cl-parsecommandlineoptions-function) takes raw `argc` and `argv` arguments directly, where `argv` is a `char**`. I was trying to implement my argument parser so that it can be invoked from a sane C++ API (Say, using a vector of string views), and I was wondering if any of the array lib views could be converted directly or indirectly to a `char**`.

Thanks in advance.

**Comment by foonathan** [comment]
If you have an `array_view<char*>`, `.data()` gives you a `char**`. If you have an `array_view<std::string_view>` you can't get a `char**` because there is no array of char pointers anywhere.
